### PR TITLE
Increase gas to 30 

### PR DESCRIPTION
**Pull request by harjas27**
* Updating the gas from 1 gwei to 30 gwei in all the transactions
* Update the `hash` and `signed-raw-tx` for those transactions

### CODE REVIEW

**Comment by rlan35** [comment]
How is this tested to make sure it passes all the tests?

**Comment by harjas27** [comment]
I had commented out this https://github.com/rlan35/harmony/blob/aaad61f6145f8985e0b5d111d439d03ed34f4e6f/node/node.go#L1033 , and created a custom image with the update `harmony` repo and tests in this PR. 
The old transactions (without 30gwei) will result in failure -`underpriced`

**Comment by sophoah** [comment]
Hey @harjas27 let's continue our discussion in public when possible. And I'll reply to your question here. let's enabled the the staking transaction test as well and make sure they can run successfully.

**Comment by harjas27** [comment]
for the staking transactions, I am unable to send the signed tx. 
This is my code snippet for generating one of the `CreateValidator` transaction:
```
stx = {
    "validatorAddress": "one109r0tns7av5sjew7a7fkekg4fs3pw0h76pp45e",
    "name": "test",
    "identity": "test0",
    "website": "test",
    "security-contact": "test",
    "details": "test",
    "rate": "0.1",
    "max-rate": "0.9",
    "max-change-rate": "0.05",
    "min-self-delegation": 10000000000000000000000,
    "max-total-delegation": 10000000000000000000000000,
    "bls-public-keys": ['0x4f41a37a3a8d0695dd6edcc58142c6b7d98e74da5c90e79b587b3b960b6a4f5e048e6d8b8a000d77a478d44cd640270c'],
    "nonce": "0x0",
    'directive': staking_structures.Directive.CreateValidator,
    "chainId": 2,
    "gasLimit": 21000,
    "gasPrice": 30000000000,
    "amount": 10000000000000000000000,
}
signed_raw_tx = staking_signing.sign_staking_transaction(stx, private_key = private_key)
print(tx_use, signed_raw_tx) 
```
But when I send this using `hmyv2_sendRawStakingTransaction`, it returns : 
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rlp: expected input list for []bls.SerializedSignature, decoding into (types.CreateValidator).SlotKeySigs"}}
```

**Comment by sophoah** [comment]
did you wait for epoch 2 when the staking epoch start ? 
based on the error message, I wondered if the bls key was actually correctly being added into the signed tx.

When using the CLI, I need to specify the folder location of the bls key, ie if I am in the root folder of that github repo, I would create the validator with the below cli snippet
```
hmy --node="http://localhost:9598" staking create-validator --validator-addr one109r0tns7av5sjew7a7fkekg4fs3pw0h76pp45e --name "Harmony External Validator node" --identity Harmony  --website harmony.one --security-contact Harmony --details "Harmony External Validator node" --rate 0.1 --max-rate 1 --max-change-rate 0.05 --min-self-delegation 10000 --max-total-delegation 10000000000 --amount 10000 --bls-pubkeys  4f41a37a3a8d0695dd6edcc58142c6b7d98e74da5c90e79b587b3b960b6a4f5e048e6d8b8a000d77a478d44cd640270c  --bls-pubkeys-dir localnet/configs/
```

**Comment by sophoah** [comment]
@harjas27 if that helped, last week I was helping with PR4100 and needed a stable external validator on localnet. We managed to have a stable elected validator by updating the block per epoch to 60 (now 10)

**Comment by harjas27** [comment]
@sophoah the transactions have been updated with the new gas, but the test `test_get_median_raw_stake_snapshot` is still failing, working on that

**Comment by harjas27** [comment]
@sophoah the gas fees is updated now. However the test `test_get_median_raw_stake_snapshot` is still failing.
The validator gets elected, in response of `hmy_getSuperCommittees`, I get :
```
{"bls-public-key":"4f41a37a3a8d0695dd6edcc58142c6b7d98e74da5c90e79b587b3b960b6a4f5e048e6d8b8a000d77a478d44cd640270c","earning-account":"one109r0tns7av5sjew7a7fkekg4fs3pw0h76pp45e","effective-stake":"10000000000000000000000.000000000000000000","is-harmony-slot":false,"raw-stake":"10000000000000000000000.000000000000000000","voting-power-%":"0.320000000000000002","voting-power-unnormalized":"1.000000000000000000"}
```
But for `hmyv2_getMedianRawStakeSnapshot`, it is:
```
{"jsonrpc":"2.0","id":1,"result":{"epos-median-stake":"0.000000000000000000","epos-slot-candidates":[],"epos-slot-winners":[],"max-external-slots":6}}
```

**Comment by sophoah** [comment]
if the validator is seen elected in `hmy_getSuperCommittees` but `hmyv2_getMedianRawStakeSnapshot` doesn't return the correct data that might be a bug in the codebase used for the test, did you you pull the latest commit for that ? there was some test done on the localnet https://github.com/harmony-one/harmony/pull/4100 (done manually) not sure if new updates broke it or not.

**Comment by harjas27** [comment]
I have tried with both - code before that PR was merged and latest, the test of failing in both cases

**Comment by sophoah** [comment]
Hey, if that is the case, then it should be all good, the localnet validator election instability is a known issue. We need to increase the block per epoch from 10 to 60 to have it work stable. Can you do so and post here the end result? I'll work out separately the localnet number of blocks

**Comment by MaxMustermann2** [comment]
> for the staking transactions, I am unable to send the signed tx. This is my code snippet for generating one of the `CreateValidator` transaction:
> 
> ```
> stx = {
>     "validatorAddress": "one109r0tns7av5sjew7a7fkekg4fs3pw0h76pp45e",
>     "name": "test",
>     "identity": "test0",
>     "website": "test",
>     "security-contact": "test",
>     "details": "test",
>     "rate": "0.1",
>     "max-rate": "0.9",
>     "max-change-rate": "0.05",
>     "min-self-delegation": 10000000000000000000000,
>     "max-total-delegation": 10000000000000000000000000,
>     "bls-public-keys": ['0x4f41a37a3a8d0695dd6edcc58142c6b7d98e74da5c90e79b587b3b960b6a4f5e048e6d8b8a000d77a478d44cd640270c'],
>     "nonce": "0x0",
>     'directive': staking_structures.Directive.CreateValidator,
>     "chainId": 2,
>     "gasLimit": 21000,
>     "gasPrice": 30000000000,
>     "amount": 10000000000000000000000,
> }
> signed_raw_tx = staking_signing.sign_staking_transaction(stx, private_key = private_key)
> print(tx_use, signed_raw_tx) 
> ```
> 
> But when I send this using `hmyv2_sendRawStakingTransaction`, it returns :
> 
> ```
> {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rlp: expected input list for []bls.SerializedSignature, decoding into (types.CreateValidator).SlotKeySigs"}}
> ```

I think you've fixed this, but the branch `validator-sigs` on my `pyhmy` fork has this commit https://github.com/MaxMustermann2/pyhmy/commit/4f266619faa4924f64d4de4e48b919ee00e5f905 which should help you correct that, if still needed.

**Comment by harjas27** [comment]
> > for the staking transactions, I am unable to send the signed tx. This is my code snippet for generating one of the `CreateValidator` transaction:
> > ```
> > stx = {
> >     "validatorAddress": "one109r0tns7av5sjew7a7fkekg4fs3pw0h76pp45e",
> >     "name": "test",
> >     "identity": "test0",
> >     "website": "test",
> >     "security-contact": "test",
> >     "details": "test",
> >     "rate": "0.1",
> >     "max-rate": "0.9",
> >     "max-change-rate": "0.05",
> >     "min-self-delegation": 10000000000000000000000,
> >     "max-total-delegation": 10000000000000000000000000,
> >     "bls-public-keys": ['0x4f41a37a3a8d0695dd6edcc58142c6b7d98e74da5c90e79b587b3b960b6a4f5e048e6d8b8a000d77a478d44cd640270c'],
> >     "nonce": "0x0",
> >     'directive': staking_structures.Directive.CreateValidator,
> >     "chainId": 2,
> >     "gasLimit": 21000,
> >     "gasPrice": 30000000000,
> >     "amount": 10000000000000000000000,
> > }
> > signed_raw_tx = staking_signing.sign_staking_transaction(stx, private_key = private_key)
> > print(tx_use, signed_raw_tx) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But when I send this using `hmyv2_sendRawStakingTransaction`, it returns :
> > ```
> > {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rlp: expected input list for []bls.SerializedSignature, decoding into (types.CreateValidator).SlotKeySigs"}}
> > ```
> 
> I think you've fixed this, but the branch `validator-sigs` on my `pyhmy` fork has this commit [MaxMustermann2/pyhmy@4f26661](https://github.com/MaxMustermann2/pyhmy/commit/4f266619faa4924f64d4de4e48b919ee00e5f905) which should help you correct that, if still needed.

yes I used the `go-sdk` to sign the validator txs

**Comment by harjas27** [comment]
@sophoah Verified that all tests pass after updating the block per epoch to 60 in localnet config

**Comment by sophoah** [comment]
@harjas27 can you paste the test logs here, then we should be able to merge that PR

**Review by MaxMustermann2 — APPROVED** [review]
LGTM, many thanks for adding back the previously excluded staking tests!

**Comment by sophoah** [comment]
hey @harjas27 thanks for your help

**Pull request merged**
